### ISSUE TITLE
missing very basic tools ip or ifconfig, tar, ... poor usability of this fedora base image

### ISSUE THREAD

**Issue by c0b** [fedora-cloud/docker-brew-fedora#33]
I'm from https://hub.docker.com/_/fedora/ to here, for an occasional case, I want to give fedora base docker image a try, instead of the default debian / ubuntu image, first I don't see a default CMD setup, have to run the image with /bin/bash, then from the shell I want to tell what's current ip addr allocated, but either ip or ifconfig is missing, I found more basic tools are missing, the usability is very poor

if you're arguing for small image size, then I found iptables is available from the container, since it's unprivileged by default, it doesn't work because some capabilities dropped, even it can work from a privileged container, but who needs iptables tool inside the container?

```
[root@4b814453157b /]# iptables -nvL
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
[root@4b814453157b /]# 
```

what's the meaning of you guys maintaining this base image? if not trying to make it useful?

**Comment by c0b** [comment]
`docker inspect` from the host is another way to tell ip addr of a container, but I want to tell the ip addr from the container as well, is there an alternative to ip or ifconfig?

**Comment by c0b** [comment]
@maxamillion have thoughts on this? I just got you from docker-library/official-images#1198 why can't make `fedora` more useful?

**Comment by maxamillion** [comment]
As mentioned in the [README.md](https://github.com/fedora-cloud/docker-brew-fedora/blob/master/README.md), this is just an upload space for the spin-kickstarts project where the kickstart that generates the image is maintained. These concerns and discussions should be taken up with the Fedora developer community, either [Fedora Devel List](https://admin.fedoraproject.org/mailman/listinfo/devel) or [Fedora Cloud List](https://admin.fedoraproject.org/mailman/listinfo/cloud). 

I'm open to changes but I'd rather see a community consensus around the change instead of me (or anyone) just dictating the change.

**Comment by crquan** [comment]
no, i don't even know how to deal with fedora developers, but here the issue #33 is reported to maintainers whoever is behind https://hub.docker.com/_/fedora/ , to me the `just an upload space` is not a good excuse, and to make the fedora docker image useful is the job of maintainers here, nobody says you have to keep up with spin-kickstarts project, if they are not qualified on their seats, why not implement in a different way?
if you don't care, i wouldn't care, will just mark `https://hub.docker.com/_/fedora/` as not usable one: lacking some essential tools and provides superfluous tools; not optimal base image.

**Comment by crquan** [comment]
For example: at least something you can do is to set a default shell, when user runs `docker run -it --rm fedora`, make sure user get something to run, not an error like `Error response from daemon: No command specified`

```
CMD ["/bin/bash"]
```

https://github.com/tianon/docker-brew-ubuntu-core/blob/3c355946fd5164da3f31063a5c5f249c826f7071/trusty/Dockerfile

**Comment by mattdm** [comment]
@crquan I think we really do want the base image to stay minimal, and possibly even become _more_ minimal. We've talked, though, about having a "with batteries" layered image built right on top of that, which have a more familiar environment. 

That said, what @maxamillion is saying is that you've filed this issue in a github repo which is unrelated to that. The lists that he suggests really are a good place for talking about the base image. However, if you want to say on GitHub, and want to discuss _layered_ images (including the "batteries included" idea), see https://github.com/fedora-cloud/Fedora-Dockerfiles instead of here.

**Comment by crquan** [comment]
then would you remove iptables and set up a default CMD ?

**Comment by mattdm** [comment]
@crquan Possibly the people working on it will. But please see https://github.com/fedora-cloud/docker-brew-fedora/blob/master/README.md for where to file requests like that for proper discussion — this ticket just plain doesn't go to the right group.

**Comment by siddharthvipul** [comment]
issue related to the EOL versions. Please reopen if you notice this in newer images
