### ISSUE TITLE
Move the "latest" tag to the Fedora 32 image

### ISSUE THREAD

**Issue by nmusatti** [fedora-cloud/docker-brew-fedora#74]
Fedora 32 has been the latest official release for a few weeks now, but the "latest" tag is still associated with Fedora 31.

**Comment by cverna** [comment]
@siddharthvipul as discussed can you look after this issue ? thanks :)

**Comment by siddharthvipul** [comment]
@cverna 
yes! thank you :)
I will work on it

**Comment by sc0w** [comment]
why closing?

it was already fixed?

**Comment by siddharthvipul** [comment]
> why closing?
> 
> it was already fixed?

I have already sent the PR, but due to the DC move, there were some problems... I will push the updated containers once again as soon as it's fixed
Please check the updated library latest tag

https://github.com/fedora-cloud/official-images/blob/f0322f89479589c2c20bf68143a82d533943e527/library/fedora#L60

**Comment by cverna** [comment]
ha sorry I thought this was fixed. @siddharthvipul  we should just update the tag then and later the images once we have them working

**Comment by Dridi** [comment]
It looks like it's fixed in Fedora's container registry but not on DockerHub. I switched to Fedora's registry because it's the only registry where we get official fedora-minimal images and I had forgotten about those.

Thanks!
